Multi-RAD RADSim from dev-abnash
andrewboutros/rad-flow pull request #29
Opened 2024-07-10 04:45 UTC by abnashkb

Draft pull request for multi-RAD RADSim. This code supports single-RAD and multi-RAD simulation. A unified configuration file describes configurations for varying RADs in addition to parameters that are shared across the entire cluster of RADs.

2024-08-21 22:30 UTC, andrewboutros requested changes
Hi @abnashkb! Thanks a lot for preparing this huge PR. It is a lot of work -- good job :)

I finished my first round of review and added my comments. I think we will probably need another round of review when you are done addressing these comments. Let me know if you would like to meet sooner than Sep 4 to discuss any of my comments.

2024-08-21 22:30 UTC, andrewboutros commented on rad-sim/sim/radsim_cluster.cpp
> +    for (int i = 0; i < num_rads; i++) {
loop variable name

2024-08-21 22:30 UTC, andrewboutros commented on rad-sim/sim/radsim_cluster.hpp
> +
This file is also very important. It should include big-picture comments describing the class and what it is used for.

2024-08-21 22:30 UTC, andrewboutros commented on rad-sim/sim/radsim_config.cpp
> +// Adds a new integer configuration knob
See my previous comment on unifying the API for per-RAD and shared knobs

2024-08-21 22:30 UTC, andrewboutros commented on rad-sim/sim/radsim_inter_rad.hpp
> +struct axis_fields {
This is very similar to the struct used in portal module. Check my comment on unifying it as a shared NoC infrastructure struct.

2024-08-21 22:30 UTC, andrewboutros commented on rad-sim/sim/radsim_inter_rad.hpp
> +
Missing big-picture comments for this class.

2024-08-21 22:30 UTC, andrewboutros commented on rad-sim/sim/radsim_inter_rad.hpp
> +        //sc_fifo<sc_bv<DATAW>> data_in_rad1 = sc_fifo<sc_bv<DATAW>>(2); //2 slots for now
clean up commented out code.

2024-08-21 22:30 UTC, andrewboutros commented on rad-sim/sim/radsim_inter_rad.cpp
> +RADSimInterRad::ConnectRadPair(int i, int j) {
This is supposed to be an empty function? If not needed we should remove from .cpp and .hpp files.

2024-08-21 22:30 UTC, andrewboutros commented on rad-sim/sim/radsim_inter_rad.cpp
> +                    /* START FOR DEBUG */
Clean up all commented out code

2024-08-21 22:30 UTC, andrewboutros commented on rad-sim/sim/radsim_inter_rad.cpp
> +            if (bw_counter < radsim_config.GetIntKnobShared("inter_rad_bw_accept_cycles")) { //>= bw_limit) {
Should add a comment describing how this bandwidth counter achieves the desired functionality.

2024-08-21 22:30 UTC, andrewboutros commented on rad-sim/sim/radsim_inter_rad.cpp
> +            //IMPORTANT: currently does not accept backpressure. Portal module must create a buffer for backpressure on the RAD's NoC
I think it is critical that inter-RAD and Portal modules support back-pressure.

2024-08-21 22:30 UTC, andrewboutros commented on rad-sim/sim/radsim_module.hpp
> +class RADSimDesignContext; //AKB ADDED
Not sure why this is here. Isn't including `design_context.hpp` enough?

2024-08-21 22:30 UTC, andrewboutros commented on rad-sim/sim/sim.log
> +[TRACE] npu_system.npu_inst.axis_vector_elementwise_0.evrf_0 @ 164: Tag is updated to 1
This file should be added to .gitignore and not checked in the repo

2024-08-21 22:30 UTC, andrewboutros commented on rad-sim/sim/sim.trace
> -
Same. Add to .gitignore and don't check it in the repo.

2024-08-21 22:30 UTC, andrewboutros commented on rad-sim/sim/radsim_telemetry.cpp
> +  entry.dest_node = (~(0xff << AXIS_DEST_FIELDW)) & dest; //extract only local NoC node. ignore any remote NoC node set for inter-rad network.
I don't fully understand the logic in this line. What if the field that we need to mask out is wider than 8 bits (0xff)?

2024-08-21 23:29 UTC, vaughnbetz requested changes
Thanks for the major upgrade Abnash!
Biggest change is to remove the various cmake products, and update .gitignore.
Also, a few comments that say things like "AB: updated to ..." should be replaced by just describing what the functionality is.

General comment for Andrew: over time, it's good to add high-level (file scope etc.) comments.

2024-08-21 23:29 UTC, vaughnbetz commented on docs/rad-sim-rtl-code.rst
> +WARNING/TODO: this guide has not been updated or tested with multi-RAD RADSim. This is functional for single-RAD RADSim.
Would be good to make any needed updates since it isn't clear how someone should proceed if we've upgraded to multi-RADSim but haven't updated the docs.

2024-08-21 23:29 UTC, vaughnbetz commented on rad-sim/config.py
> +    main_cpp_file.write("\treturn cluster->all_rads[0]->GetSimExitCode();\n")
Maybe 0 is the main sim/thread?  In that case a comment should say that index 0 is special (and how).

2024-08-21 23:29 UTC, vaughnbetz commented on rad-sim/sim/noc/aximm_master_adapter.hpp
> +  unsigned int _rad_id;
General comment (more for Andrew): it is good to have a comment at the top of a file saying what the purpose of the overall file is so people know when adding new code if it should go in there.  I wouldn't hold up this PR for that, but wanted to mention it.

2024-08-28 05:41 UTC, abnashkb commented on rad-sim/example-designs/add/add_driver.cpp
> +    client_tlast.write(numbers_to_send.size() <= TOTAL_RADS-1); //bc sending to TOTAL_RADS-1 mult RADs, so both receive the last flag
This would set `tlast` to high when both RADs are each receiving the last of the 5 addends. If we have 2 RADs, `TOTAL_RADS-1` is 1, so `tlast` would be high if `numbers_to_send` has size 1 or 0, which means each RAD is getting the last number. This testbench sends numbers in groups so `numbers_to_send` is of the format [addend 1 for RAD 1, addend 1 for RAD 2, addend 2 for RAD 1, addend 2 for RAD 2, ...].

2024-09-10 04:34 UTC, abnashkb commented on docs/rad-sim-code-structure.rst
> +    |  |  |- uni_config.yml
`uni_` stands for unified. This naming convention was helpful for me to track different config file structures during development. I agree with your feedback and have now renamed all uses of `uni_config.yml` to `config.yml`

2024-09-10 04:47 UTC, abnashkb commented on docs/rad-sim-code-structure.rst
> +* The ``radsim_cluster`` class in ``radsim_cluster.{cpp/hpp}`` stores details for the cluster of multiple RADs for the RADSim simulation. This is the top-level of the hierarchy for multiple device si
Done: this was a typo in the documentation as the class name was already `CamelCase`. Also adjusted the description.

2024-09-10 04:59 UTC, abnashkb commented on docs/rad-sim-code-structure.rst
> +* The ``design_system`` class in ``design_system.hpp`` is a generalized parent class used per design. The design_system wraps around the device-under-test (DUT) and testbench. Each design in the exam
done

2024-09-10 05:01 UTC, abnashkb commented on docs/rad-sim-code-structure.rst
> +5. Raise per-RAD flag to stop simulation when all outputs are received across all devices under simulation
done

2024-09-10 05:01 UTC, abnashkb commented on docs/rad-sim-code-structure.rst
> +* Utility functions functions and struct definitions are in ``radsim_utils.{cpp/hpp}``.
done

2024-09-10 05:03 UTC, abnashkb commented on docs/rad-sim-code-structure.rst
> +**Config Configuration Parameters**
done

2024-09-10 05:04 UTC, abnashkb commented on docs/rad-sim-code-structure.rst
> +:menuselection:`queue_sizes` are the sizes for the queue used for each
done

2024-09-10 05:06 UTC, abnashkb commented on docs/rad-sim-code-structure.rst
> +:menuselection:`config_files` are the filenames of the files specifying the memory configuration per DRAM
done

2024-09-10 05:06 UTC, abnashkb commented on docs/rad-sim-code-structure.rst
> +:menuselection:`clk_periods` are the clock periods for the configuration
done

2024-09-10 05:07 UTC, abnashkb commented on rad-sim/config.py
> +    #commented out below bc yaml file now explicitly sets sim_driver_perid
done

2024-09-10 05:08 UTC, abnashkb commented on rad-sim/config.py
> +    radsim_params_header_file = open(radsim_header_params["radsim_root_dir"] + "/sim/radsim_defines.hpp", "w") #AKB created temp file to test
removed

2024-09-10 05:08 UTC, abnashkb commented on rad-sim/config.py
> +        # if param == 'inter_rad_latency':
removed

2024-09-10 05:09 UTC, abnashkb commented on rad-sim/config.py
> +    #os.system("cd build; cmake -DDESIGN:STRING=" + design_name + " ..; cd ..;")
removed

2024-09-10 05:09 UTC, abnashkb commented on rad-sim/config.py
> +    #os.system("cd build; cmake -DDESIGN:STRING=\"" + 'add' + "\" ..; cd .;")
removed

2024-09-10 05:09 UTC, abnashkb commented on rad-sim/test/dlrm_test.sh
> +cp -f ../example-designs/dlrm/config.yml ../uni_config.yml
done

2024-09-10 05:10 UTC, abnashkb commented on rad-sim/uni_config.yml
> +noc:
done

2024-09-10 05:10 UTC, abnashkb commented on rad-sim/config.py
> +        # "sim_driver_period": 5.0,
removed

2024-09-10 05:12 UTC, abnashkb commented on rad-sim/example-designs/CMakeLists.txt
> +#add_subdirectory(add)
done

2024-09-10 05:13 UTC, abnashkb commented on rad-sim/example-designs/add/add_driver.hpp
> +  add_driver(const sc_module_name &name, RADSimDesignContext* radsim_design_); //AKB ADDED last arg
removed

2024-09-10 05:13 UTC, abnashkb commented on rad-sim/example-designs/add/add_driver.hpp
> +  RADSimDesignContext* radsim_design; //AKB ADDED: store ptr passed into constructor for use in source() and sink()
removed

2024-09-10 05:14 UTC, abnashkb commented on rad-sim/example-designs/add/add_system.cpp
> +add_system::add_system(const sc_module_name &name, sc_clock *driver_clk_sig, RADSimDesignContext* radsim_design) // AKB: added last 3 args
removed

2024-09-10 05:17 UTC, abnashkb commented on rad-sim/example-designs/add/modules/adder.cpp
> +      uint64_t dst_addr = radsim_design->GetPortDestinationID(dst_port_name); //AKB changed to ptr deref
removed -- these comments were used during development

2024-09-10 05:17 UTC, abnashkb commented on rad-sim/example-designs/add/modules/adder.cpp
> +    /*if (adder_tdata_tlast_fifo.size() > 0) { //fifo not empty
removed

2024-09-10 05:20 UTC, abnashkb commented on rad-sim/sim/design_context.cpp
> +    std::cout << "design_context.cpp: port_name and is_aximm_master and is_axis_master " << port_name << " " << is_aximm_master << " " << is_axis_master << std::endl;
used for debug, removed

2024-09-10 05:20 UTC, abnashkb commented on rad-sim/sim/design_context.cpp
> +  //AKB ADDED:
removed

2024-09-10 05:21 UTC, abnashkb commented on rad-sim/sim/design_context.cpp
> +  std::cout << "rad_id " << rad_id << " has num_nocs " << num_nocs << std::endl;
used for debug, removed

2024-09-10 05:22 UTC, abnashkb commented on rad-sim/sim/design_context.cpp
> +//AKB ADDED: returns info (because private member) of if the RAD is done simulation
done

2024-09-10 05:23 UTC, abnashkb commented on rad-sim/sim/design_context.hpp
> +//extern RADSimDesignContext radsim_design; //AKB: commented out
correct, removed

2024-09-10 05:24 UTC, abnashkb commented on rad-sim/sim/design_top.hpp
> +        axis_slave_port design_top_portal_axis_slave; //TODO: add back here, for now just directly putting into child class add_top
cleaned up this file.

2024-09-10 05:24 UTC, abnashkb commented on rad-sim/sim/design_top.hpp
> +            // portal_inst->rst(rst); //AKB: commented out to try to fix Info: (I804) /IEEE_Std_1666/deprecated: interface and/or port binding in port constructors is deprecated
agreed, removed

2024-09-10 05:25 UTC, abnashkb commented on rad-sim/sim/dram/mem_controller.hpp
> +                 std::string init_filename = ""); //AKB: added radsim_design, note that argument(s) with defaults must be at end
removed

2024-09-10 05:25 UTC, abnashkb commented on rad-sim/sim/noc/axis_interface.hpp
> +    //AKB ADDED few lines below TO TEST
removed

2024-10-13 07:18 UTC, abnashkb commented on rad-sim/sim/noc/axis_slave_adapter.hpp
> +  unsigned int _portal_id; //AKB ADDED FOR TO-DO-MR
Removed completed to-do notes and added explanation to comments in axis_slave_adapter.hpp/cpp.

2024-10-13 07:37 UTC, abnashkb commented on docs/rad-sim-rtl-code.rst
> +WARNING/TODO: this guide has not been updated or tested with multi-RAD RADSim. This is functional for single-RAD RADSim.
Removed warning and added notes on changes needed for RTL-based designs for multi-RAD-Sim.

2024-10-13 07:45 UTC, abnashkb commented on rad-sim/example-designs/add/CMakeFiles/cmake.check_cache
done, deleted CMakeFiles directory.

2024-10-13 07:45 UTC, abnashkb commented on rad-sim/example-designs/add/CMakeFiles/CMakeOutput.log
done, deleted CMakeFiles directory.

2024-10-13 07:57 UTC, abnashkb commented on rad-sim/example-designs/add/CMakeFiles/3.16.3/CompilerIdC/a.out
Done, deleted CMakeFiles directory. Added .gitignore file with CMakeFiles and MakeFiles excluded.

2024-10-13 08:05 UTC, abnashkb commented on docs/rad-sim-developer.rst
> +WARNING/TODO: this guide has not been updated or tested with multi-RAD RADSim. This is functional for single-RAD RADSim.
Unsure about expected results from ``python -m unittest discover .``. Leaving this unresolved for discussion.

2024-10-13 08:09 UTC, abnashkb commented on rad-sim/sim/sim.log
> +[TRACE] npu_system.npu_inst.axis_vector_elementwise_0.evrf_0 @ 164: Tag is updated to 1
done earlier, marking as closed.

2024-10-13 08:14 UTC, abnashkb commented on rad-sim/sim/sim.trace
> -
done

2024-10-13 08:15 UTC, abnashkb commented on rad-sim/config.py
> +    main_cpp_file.write("\treturn cluster->all_rads[0]->GetSimExitCode();\n")
RAD 0 is used as the default to return the simulation exit code.

2024-10-13 08:18 UTC, abnashkb commented on rad-sim/example-designs/add/CMakeCache.txt
> +# This is the CMakeCache file.
done.

2024-10-13 08:19 UTC, abnashkb commented on rad-sim/example-designs/add/CMakeFiles/3.16.3/CMakeCCompiler.cmake
> +set(CMAKE_C_COMPILER "/usr/bin/cc")
done.

2024-10-14 08:13 UTC, abnashkb commented on docs/rad-sim-code-structure.rst
> +These files define a design_top class which in turn defines a SystemC module (``sc_module``) that instantiates all the modules in the design and connects any
The other instance of under_scored (`radsim_inter_rad`) class name has been changed to `RADSimInterRad` in code and documentation.

For the comment on "which in turn defines a SystemC module", I would like to keep this explanation to make the chain of definitions clear to future developers.

2024-10-14 08:14 UTC, abnashkb commented on docs/rad-sim-code-structure.rst
> +There may be multiple ``config <configname>`` sections, with each describing a configuration that applies to a specified number of RADs.
made this revision.

2024-10-14 08:16 UTC, abnashkb commented on rad-sim/config.py
> +    for j in range(len(cluster_knobs["cluster_configs"])): #curr_config_num in range(num_configs):
good point, done.

2024-10-14 08:21 UTC, abnashkb commented on rad-sim/config.py
> +        for i in range(booksim_params[curr_config_num]["noc_num_nocs"]):
done, replaced with noc_idx

2024-10-16 06:04 UTC, abnashkb commented on rad-sim/example-designs/dlrm/CMakeLists.txt
> +  modules/portal.cpp
fixed.

2024-10-16 06:05 UTC, abnashkb commented on rad-sim/example-designs/dlrm/CMakeLists.txt
> +  modules/portal.hpp
fixed.

2024-10-16 06:06 UTC, abnashkb commented on rad-sim/example-designs/mlp/compiler/gen_testcase.py
> +clocks_file.write('portal_inst 0 0\n')
removed portal module creation in single-rad example designs, corrected any code dependences.

2024-10-16 06:12 UTC, abnashkb commented on rad-sim/example-designs/mlp/mlp_system.cpp
>    sc_module(name) {
The base class `RADSimDesignSystem` does not have any members to be initialized so no constructor call is needed. Its class member gets set to a pointer within the `mlp_system` constructor code.

2024-10-16 06:13 UTC, abnashkb commented on rad-sim/example-designs/mlp_int8/compiler/gen_testcase.py
> +placement_file.write('portal_inst 0 16 axis\n')
done.

2024-10-16 06:14 UTC, abnashkb commented on rad-sim/example-designs/mlp_int8/mlp_int8_system.cpp
>    sc_module(name) {
Same as https://github.com/andrewboutros/rad-flow/pull/29#discussion_r1802420901. Leaving comment thread unresolved for further discussion.

2024-10-16 06:15 UTC, abnashkb commented on rad-sim/example-designs/mult/CMakeCache.txt
> +# This is the CMakeCache file.
done

2024-10-16 06:15 UTC, abnashkb commented on rad-sim/example-designs/npu/npu.clks
> +portal_inst 0 0
done

2024-10-16 06:18 UTC, abnashkb commented on rad-sim/sim/CMakeLists.txt
> +  FOREACH(DESIGN_NAME ${DESIGN_NAMES})
fixed

2024-10-16 06:21 UTC, abnashkb commented on rad-sim/sim/design_context.cpp
> +  // std::string radsim_knobs_filename = "/sim/radsim_knobs";
cleaned up file earlier.

2024-10-16 06:23 UTC, abnashkb commented on rad-sim/sim/design_context.cpp
> +uint64_t DeterminedBaseAddress(int noc_id, int node_id, int rad_id) {
done.

2024-10-16 06:31 UTC, abnashkb commented on rad-sim/sim/design_context.hpp
> +  std::string portal_slave_name;
done

2024-10-16 06:33 UTC, abnashkb commented on rad-sim/sim/dram/DRAMsim3/Makefile
> -# ONLY use this makefile if you do NOT have a cmake 3.0+ version
removed

2024-10-16 06:39 UTC, abnashkb commented on rad-sim/sim/noc/noc0_rad0_config
> +// Topology
done and done.

2024-10-16 06:51 UTC, abnashkb commented on rad-sim/example-designs/dlrm/modules/collector.cpp
> +  } else if (radsim_design->rad_id == 1) {
the example design uses two DLRMs as proof of concept, with the rad_id used to select which functions to enable.

2024-10-16 06:51 UTC, abnashkb commented on rad-sim/example-designs/dlrm/modules/embedding_lookup.cpp
> +  } else if ((radsim_design->rad_id == 0)) {
same as https://github.com/andrewboutros/rad-flow/pull/29#discussion_r1802463676

2024-10-16 06:52 UTC, abnashkb commented on rad-sim/example-designs/dlrm/modules/embedding_lookup.cpp
> +  if (radsim_design->rad_id == 0) {
same as https://github.com/andrewboutros/rad-flow/pull/29#discussion_r1802463676

2024-10-16 06:53 UTC, abnashkb commented on rad-sim/example-designs/dlrm/modules/mvm.cpp
> +  if (radsim_design->rad_id == 1) {
same as https://github.com/andrewboutros/rad-flow/pull/29#discussion_r1802463676

This is proof of concept for two RADs and the main benefit of enabling certain modules in this way is the ability to reuse the same design directory for multiple RADs. Future work can split this into two separate RADs only containing the required modules.

2024-10-16 07:01 UTC, abnashkb commented on rad-sim/config.py
> +                #TODO: below doesnt rlly make sense for cluster-level params, fix up
comment was outdated, removed.

2024-10-16 07:02 UTC, abnashkb commented on rad-sim/sim/noc/aximm_slave_adapter.cpp
> +  _noc_period = radsim_config.GetDoubleVectorKnobPerRad("noc_clk_period", _network_id, _rad_id);
Relegated to an issue for later work.

2024-10-16 07:09 UTC, abnashkb commented on rad-sim/sim/design_top.hpp
> +//#define DATAW 128
Done, with the exception that I think it is okay to skip the cpp file for such a brief constructor.

2024-10-16 07:12 UTC, abnashkb commented on rad-sim/sim/main.cpp
> +	RADSimInterRad* blackbox = new RADSimInterRad("inter_rad_box", inter_rad_clk_sig, cluster);
changed config.py to not generate RADSimInterRAD unless there is more than 1 RAD.

2024-10-16 07:13 UTC, abnashkb commented on rad-sim/sim/noc/axis_slave_adapter.cpp
> +  _rad_id = rad_id; // TO-DO-MR-DONE: set appropriate RAD ID through constructor
removed outdated TO-DO comments.

2024-10-16 07:14 UTC, abnashkb commented on rad-sim/sim/noc/axis_slave_adapter.hpp
> +  unsigned int _rad_id; // TO-DO-MR-DONE: RAD ID of this adapter (for multi-RAD systems)
done, also added comments explaining the new members.

2024-10-16 07:17 UTC, abnashkb commented on rad-sim/sim/noc/axis_slave_adapter.cpp
> +          sc_bv<AXIS_DESTW> booksim_flit_dest = _portal_id; // TO-DO-MR-DONE: set to portal node ID
done.

2024-10-16 07:22 UTC, abnashkb commented on rad-sim/sim/portal.cpp
> +sc_bv<AXIS_USERW> dest_device = 1; //for testing, fixed at 1 to send to RAD1 which has mult design; //#define AXIS_USERW     66
removed.

2024-10-16 07:22 UTC, abnashkb commented on rad-sim/sim/portal.cpp
> +                /* START FOR DEBUG */
done.

2024-10-16 07:23 UTC, abnashkb commented on rad-sim/sim/portal.cpp
> +//used for internal testing
done

2024-10-16 07:25 UTC, abnashkb commented on rad-sim/sim/portal.hpp
> +        //sc_in<sc_bv<DATAW>> portal_in;
done.

2024-10-16 07:27 UTC, abnashkb commented on rad-sim/sim/radsim_config.cpp
> +// Adds a new integer configuration knob
Opened issue for prev. comment.

2024-10-16 07:31 UTC, abnashkb commented on rad-sim/sim/portal.cpp
> +        //Always ready to accept from NoC because we have FIFO buffers in both directions
Yes, I have this as a TODO for future development. Created an issue to formally track.

2024-10-16 07:37 UTC, abnashkb commented on rad-sim/sim/radsim_inter_rad.hpp
> +        //sc_fifo<sc_bv<DATAW>> data_in_rad1 = sc_fifo<sc_bv<DATAW>>(2); //2 slots for now
done.

2024-10-16 07:37 UTC, abnashkb commented on rad-sim/sim/radsim_inter_rad.cpp
> +RADSimInterRad::ConnectRadPair(int i, int j) {
was used earlier, removed now.

2024-10-16 07:38 UTC, abnashkb commented on rad-sim/sim/radsim_inter_rad.cpp
> +                    /* START FOR DEBUG */
done

2024-10-16 07:39 UTC, abnashkb commented on rad-sim/sim/portal.cpp
> +}
done.

2024-10-16 07:51 UTC, abnashkb commented on rad-sim/sim/radsim_inter_rad.cpp
> +            if (bw_counter < radsim_config.GetIntKnobShared("inter_rad_bw_accept_cycles")) { //>= bw_limit) {
done.

2024-10-16 07:51 UTC, abnashkb commented on rad-sim/sim/radsim_inter_rad.hpp
> +
done

2024-10-16 07:58 UTC, abnashkb commented on rad-sim/sim/radsim_cluster.cpp
> +    inter_rad_topo = ALL_TO_ALL;
done.

2024-10-16 08:00 UTC, abnashkb commented on rad-sim/example-designs/dlrm/modules/mvm.cpp
> +  while (true && (radsim_design->rad_id == 1)) {
same as https://github.com/andrewboutros/rad-flow/pull/29#discussion_r1802463676

2024-10-16 08:00 UTC, abnashkb commented on rad-sim/example-designs/dlrm/modules/collector.cpp
> +  } else if (radsim_design->rad_id == 1) {
Opened issue to address in future development.

2024-10-16 08:04 UTC, abnashkb commented on rad-sim/example-designs/add_multi/add_driver.cpp
> +
removed.

2024-10-16 08:05 UTC, abnashkb commented on rad-sim/example-designs/add_multi/config.yml
> +noc:
removed.

2024-10-25 04:31 UTC, abnashkb commented on docs/rad-sim-two-rad-dlrm-example.rst
> +    $ python config.py dlrm #dlrm is name of design directory within example-designs parent directory
done.

2024-10-25 05:13 UTC, abnashkb commented on rad-sim/sim/radsim_telemetry.cpp
> +  entry.dest_node = (~(0xff << AXIS_DEST_FIELDW)) & dest; //extract only local NoC node. ignore any remote NoC node set for inter-rad network.
fixed.

2024-10-25 05:17 UTC, abnashkb commented on rad-sim/sim/radsim_inter_rad.cpp
> +            //IMPORTANT: currently does not accept backpressure. Portal module must create a buffer for backpressure on the RAD's NoC
Opened issue https://github.com/andrewboutros/rad-flow/issues/34

2024-10-25 05:17 UTC, abnashkb commented on rad-sim/example-designs/mult/config.yml
> +noc:
fixed.

2024-10-25 05:18 UTC, abnashkb commented on rad-sim/example-designs/add/add_driver.cpp
> +    // numbers_to_send.push(r_num);
fixed.

2024-10-25 05:20 UTC, abnashkb commented on rad-sim/example-designs/add/add_driver.cpp
> +    client_tlast.write(numbers_to_send.size() <= TOTAL_RADS-1); //bc sending to TOTAL_RADS-1 mult RADs, so both receive the last flag
Reverted back to single-RAD design that works with multi-RAD code. Future work can add my multi-RAD experiments, as per this issue: https://github.com/andrewboutros/rad-flow/issues/35

2024-10-25 05:21 UTC, abnashkb commented on rad-sim/example-designs/add/add_driver.cpp
> +  while (!(response_valid.read() && portal_recvd.read())) {
Removed from current PR.

2024-10-25 05:22 UTC, abnashkb commented on rad-sim/example-designs/add/modules/adder.cpp
> +    << adder_tlast_fifo_rdata_signal << clk; //AKB: must be sensitive to clk or get occasional unexpected behaviour where rdata stagnates
Fixed.

2024-10-25 05:25 UTC, abnashkb commented on rad-sim/example-designs/add/modules/adder.cpp
> +      DEST_REMOTE_NODE(concat_dest) = 0; //for mult module on RAD 2 -- I know this, but designer would not... -- for proof of concept tho
https://github.com/andrewboutros/rad-flow/issues/37

2024-10-25 05:25 UTC, abnashkb commented on rad-sim/example-designs/add/modules/adder.hpp
> +  //to connect to fifo
no longer relevant.

2024-10-25 05:33 UTC, abnashkb commented on rad-sim/example-designs/dlrm/modules/mvm.cpp
> +      data_vector<int16_t> tdatavector(32);
done, added to the existing `dlrm_defines.hpp` file.

2024-10-25 05:33 UTC, abnashkb commented on rad-sim/example-designs/add/add_top.cpp
> +  client_inst = new client(module_name, 16, radsim_design);
done

2024-10-25 05:36 UTC, abnashkb commented on rad-sim/sim/portal.cpp
> +#include <portal.hpp>
Will require more discussion based on our previous meeting. Opened issue https://github.com/andrewboutros/rad-flow/issues/38

2024-10-25 06:01 UTC, abnashkb commented on rad-sim/example-designs/npu/compiler/add_mlp5_1536.py
> -import os
This file is still present at `rad-sim/example-designs/npu/scripts/workloads/add_mlp5_1536.py`. The contents of this file were deleted at this location because the test script seems to only place the most recently run workload file at this location.

2024-10-25 06:06 UTC, abnashkb commented on rad-sim/sim/radsim_inter_rad.cpp
> +RADSimInterRad::ConnectRadAxi(int i) {
done.

2024-10-25 06:12 UTC, abnashkb commented on rad-sim/config.py
> +                    # if param_name == "dram_config_files": #TODO: double check dram_config_files correct, had error earlier but I think I fixed earlier
This comment was outdated, removed.

2024-10-25 06:14 UTC, abnashkb commented on rad-sim/sim/noc/aximm_master_adapter.hpp
> +  unsigned int _rad_id;
Opened issue https://github.com/andrewboutros/rad-flow/issues/39

2024-10-25 06:16 UTC, abnashkb commented on rad-sim/config.py
> +    for i in range(len(cluster_knobs["cluster_configs"])):
renamed to `config_id`

2024-10-25 06:25 UTC, abnashkb commented on rad-sim/sim/radsim_cluster.cpp
> +    for (unsigned int i = 0; i < num_rads; i++) {
done.

2024-10-25 06:26 UTC, abnashkb commented on rad-sim/sim/radsim_cluster.cpp
> +RADSimCluster::CreateNewRAD(unsigned int i) {
done.

2024-10-25 06:26 UTC, abnashkb commented on rad-sim/sim/radsim_cluster.cpp
> +    for (int i = 0; i < num_rads; i++) {
done.

2024-10-25 06:27 UTC, abnashkb commented on rad-sim/sim/radsim_cluster.cpp
> +    for (int i = 0; i < num_rads; i++) {
done.

2024-10-25 06:32 UTC, abnashkb commented on rad-sim/sim/main.cpp
> +	RADSimCluster* cluster = new RADSimCluster(1);
added NUM_RADS parameter.

2024-10-25 06:46 UTC, abnashkb commented on rad-sim/sim/radsim_inter_rad.hpp
> +struct axis_fields {
Created issue https://github.com/andrewboutros/rad-flow/issues/40

2024-10-25 06:47 UTC, abnashkb commented on rad-sim/sim/portal.hpp
> +struct portal_axis_fields {
Created issue https://github.com/andrewboutros/rad-flow/issues/40

2024-10-25 07:09 UTC, abnashkb commented on rad-sim/sim/radsim_module.hpp
> +class RADSimDesignContext; //AKB ADDED
There is a circular dependence because `design_context.hpp` includes `radsim_module.hpp`. This declaration solves the issue.

2024-10-25 15:35 UTC, vaughnbetz commented
Additional tests:
- Compare simulation runtime and cycle count for dlrm design on master vs. this PR.

2024-10-25 15:36 UTC, abnashkb commented
For the dlrm design, after running dlrm.py, then rerunning only the simulation repeatedly, can consistenly get:
`Simulation Cycles from main.cpp = 6024`

Randomness is in dlrm.py. This can be made deterministic by adding seed (default seed is current time).

2024-10-25 15:44 UTC, abnashkb commented
`dev-abnash` branch, running `time make run` after having already run` python config.py dlrm` and `python dlrm.py`
Simulation Cycles from main.cpp = 6024
[100%] Built target run

real    0m49.819s
user    0m46.416s
sys     0m0.662s

2024-10-25 15:46 UTC, abnashkb commented
@andrewboutros @vaughnbetz should/can we add the new `dlrm_two_rad` and `mult` example designs into the CI tests?

2024-10-25 15:58 UTC, abnashkb commented
`main` branch, running `time make run` in the `build` dir after having already run `test/dlrm_test.sh`
```
dlrm_system.driver: Finished sending all inputs to embedding lookup module!
dlrm_system.dut.feature_interaction_inst: Got all memory responses at cycle 6145!
[==================================================] 100 %
Got 2048 output(s)!
Simulation PASSED! All outputs matching!
Simulated 19930 cycle(s)

Info: /OSCI/SystemC: Simulation stopped by user.
[100%] Built target run

real    1m56.095s
user    1m52.214s
sys     0m0.706s
```

2024-10-25 18:00 UTC, vaughnbetz commented
Memory responses come back in similar cycles, but not the exact same.  Different input config from the python script? Or something else?  If small differences are expected then it's fine.

master ran for more simulation cycles and took longer; is that because you interrupted the simulation at a different time in the two runs (i.e. it is stopped by user input when you don't see anything interesting happening?)

2024-10-29 04:54 UTC, abnashkb commented
Fixed early termination in the dlrm design on `dev-abnash` branch. Simulation output is now comparable to `main` branch:

> dlrm_system.driver: Finished sending all inputs to embedding lookup module!
> dlrm_system.dut.feature_interaction_inst: Got all memory responses at cycle 6113!
> [==================================================] 100 %
> Got 2048 output(s)!
> Simulation PASSED! All outputs matching!
> Simulated 19958 cycle(s)
> 
> Info: /OSCI/SystemC: Simulation stopped by user.
> Simulation Cycles from main.cpp = 19971
> [100%] Built target run
> 
> real    1m58.662s
> user    1m52.740s
> sys     0m0.678s

2024-11-15 13:08 UTC, andrewboutros approved these changes

2024-11-15 13:08 UTC, andrewboutros commented on docs/rad-sim-two-rad-dlrm-example.rst
> +        $ cd <rad_flow_root_dir>/rad-sim/example-designs/dlrm/compiler
I think this documentation should now use `dlrm_two_rad`?

2024-11-15 13:08 UTC, andrewboutros commented on rad-sim/example-designs/dlrm_two_rad/compiler/report.csv
Does this need to be checked in the repo?

2024-11-15 13:11 UTC, andrewboutros commented
Thanks for all the effort in getting this ready, @abnashkb! I skimmed through the code, and it looks good to me. I approved the PR and left two minor comments about a mistake (I think) in the documentation and a CSV file that I think does not need to be checked into the repo.

2024-11-15 18:00 UTC, vaughnbetz approved these changes
LGTM!

2024-11-21 08:00 UTC, abnashkb commented on rad-sim/example-designs/dlrm_two_rad/compiler/report.csv
This was checked into the current main branch, so I've kept it for consistency.

2024-11-21 08:00 UTC, abnashkb commented on docs/rad-sim-two-rad-dlrm-example.rst
> +        $ cd <rad_flow_root_dir>/rad-sim/example-designs/dlrm/compiler
Thanks for catching this! I have now updated this documentation accordingly.

2024-11-22 15:51 UTC, merged